name: Build and Publish Frontend to GitHub Packages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    # Кэширование зависимостей
    - name: Cache dependencies
      uses: actions/cache@v4.2.3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Install dependencies
      run: |
        npm install
        # npx webpack
    - name: Build frontend
      run: npm run build
    
    # Публикация в GitHub Packages
    - name: Publish to GitHub Packages
      uses: actions/upload-artifact@v4.6.2
      with:
        name: frontend-package
        path: |
          dist/
          package.json
          keep_files: false
        retention-days: 10
