name: Slider with Webpack

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout repository to the chage
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: ESLint checker
      uses: ninosaurus/eslint-check@v5.3.1
      with: 
        eslint-config-path: eslint.config.js
    
    - name: Build
      run: |
        npm install
        npx webpack
